### ISSUE TITLE
Non-existent user assigned recursively as owner of dags and plugins directories

### ISSUE THREAD

**Issue by troisimutt** [aws/aws-mwaa-local-runner#129]
When I try to deploy my aws-mwaa-local-runner, I perform the following steps:

1. Clone repo and change to this dir
2. Change the _docker-compose-local.yml_ file, so that the environment variables that I need and the volumes are set. See bellow what the resulting file is.
3. Run ./mwaa-local-env build-image
4. Run ./mwaa-local-env start

```
version: '3.7'
services:
    postgres:
        image: postgres:10-alpine
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "${PWD}/db-data:/var/lib/postgresql/data"

    local-runner:
        image: amazon/mwaa-local:2.0.2
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW_CONN_ANALYTICS_REDSHIFT=postgresql://user:pass@host:port/db
            - ACTIVE_SITE=local_site
            - GE_VALIDATION_STORE=validations_local_store
            - GE_BASE_DIR=uncommitted
            - AIRFLOW_CONN_REDSHIFT_UNLOAD_COPY_AWS_CREDS=aws://aws_key:aws_secret@?region_name=region
            - AIRFLOW__CORE__LAZY_LOAD_PLUGINS=false
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - /home/user/git_repos/my-repo/src:/usr/local/airflow/dags
            - /home/user/git_repos/my-repo/requirements.txt:/usr/local/airflow/dags/requirements.txt
            - /home/user/git_repos/my-repo/plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: local-runner
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
```

Once the local-runner started, when I ssh into the container (using `docker exec -it aws-mwaa-local-runner-202_local-runner_1 /bin/bash`), and I check the content of _/usr/local/airflow_, I see that the directories _dags_ and _plugins_ are owned by a non existing user (id=1001), whereas the _airflow_ user id is 1000. 

```
user@ubuntu:~/aws-mwaa-local-runner$ docker exec -it aws-mwaa-local-runner-202_local-runner_1 /bin/bash
[airflow@2781fba39e88 ~]$ pwd
/usr/local/airflow
[airflow@2781fba39e88 ~]$ ll
total 64
-rw-rw-r--  1 airflow airflow 36376 May 20 20:00 airflow.cfg
-rw-r--r--  1 airflow airflow     4 May 21 12:54 airflow-webserver.pid
drwxrwxr-x 15    1001    1001 12288 May 20 18:35 dags # --> owned by user 1001
drwxr-xr-x  4 airflow airflow  4096 May 20 21:08 logs
drwxrwxr-x  2    1001    1001  4096 May 16 12:28 plugins # --> owned by user 1001
-rw-rw-r--  1 airflow airflow  1271 May 20 20:00 webserver_config.py
[airflow@2781fba39e88 ~]$ id -nu 1001 # --> user 1001 doesn't exist
id: 1001: no such user
[airflow@2781fba39e88 ~]$ cat /etc/passwd # --> there is no user 1001
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
operator:x:11:0:operator:/root:/sbin/nologin
games:x:12:100:games:/usr/games:/sbin/nologin
ftp:x:14:50:FTP User:/var/ftp:/sbin/nologin
nobody:x:99:99:Nobody:/:/sbin/nologin
systemd-network:x:192:192:systemd Network Management:/:/sbin/nologin
dbus:x:81:81:System message bus:/:/sbin/nologin
saslauth:x:999:76:Saslauthd user:/run/saslauthd:/sbin/nologin
airflow:x:1000:1000::/usr/local/airflow:/bin/bash # --> uid of airflow is 1000
```
I have some dags that should write under the _dags_ directory, but they are failing due to the apparent inability of the _airflow_ user to write under this directory.
Any thoughts on what might be happening?
