### ISSUE TITLE
Specify region, aws credentials in airflow localrunner for Amazon MWAA

### ISSUE THREAD

**Issue by sambit19** [aws/aws-mwaa-local-runner#14]
I have a DAG which uses `boto3`. After installing when I placed the dag under `/dag` I get the following error. How do I sepecify region and access key? This has not been mentioned in the documentation.

> ERROR [airflow.models.dagbag.DagBag] Failed to import: /usr/local/airflow/dags/ny_taxi_brew_local.py
> local-runner_1  | Traceback (most recent call last):
> local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
> local-runner_1  |     loader.exec_module(new_module)
> local-runner_1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
> local-runner_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> local-runner_1  |   File "/usr/local/airflow/dags/ny_taxi_brew_local.py", line 61, in <module>
> local-runner_1  |     glue_databrew_client=boto3.client('databrew',region_name=region_name)
> local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/boto3/__init__.py", line 93, in client
> local-runner_1  |     return _get_default_session().client(*args, **kwargs)
> local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 263, in client
> local-runner_1  |     aws_session_token=aws_session_token, config=config)
> local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 851, in create_client
> local-runner_1  |     client_config=config, api_version=api_version)
> local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 88, in create_client
> local-runner_1  |     verify, credentials, scoped_config, client_config, endpoint_bridge)
> local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _get_client_args
> local-runner_1  |     verify, credentials, scoped_config, client_config, endpoint_bridge)
> local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 73, in get_client_args
> local-runner_1  |     endpoint_url, is_secure, scoped_config)
> local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 154, in compute_client_args
> local-runner_1  |     s3_config=s3_config,
> local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 220, in _compute_endpoint_config
> local-runner_1  |     return self._resolve_endpoint(**resolve_endpoint_kwargs)
> local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 303, in _resolve_endpoint
> local-runner_1  |     service_name, region_name, endpoint_url, is_secure)
> local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 431, in resolve
> local-runner_1  |     service_name, region_name)
> local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/botocore/regions.py", line 134, in construct_endpoint
> local-runner_1  |     partition, service_name, region_name)
> local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/botocore/regions.py", line 148, in _endpoint_for_partition
> local-runner_1  |     raise NoRegionError()
> local-runner_1  | botocore.exceptions.NoRegionError: You must specify a region.

**Comment by sambit19** [comment]
I made the changes below and it works now. I do not have the permission to create a branch/PR. 

Following has to be updated in README
If you are accessing AWS services using boto3 library then you need to provide the credentials for the local runner to authenticate. Hence export these variables on your host terminal
```
export AWS_ACCESS_KEY_ID=XXX
export AWS_SECRET_ACCESS_KEY=ZZZ
```

The updated `docker-compose-local.yml`

```

version: '3.7'
services:
    postgres:
        image: postgres:10-alpine
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "${PWD}/db-data:/var/lib/postgresql/data"

    local-runner:
        image: amazon/mwaa-local:2.0
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ${PWD}/dags:/usr/local/airflow/dags
            - ${PWD}/plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: local-runner
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

```
This might still throw an error saying region not found. You need to set the region in your dag code. E.g

```
region_name='us-east-1'
.
.
.
glue_databrew_client=boto3.client('databrew',region_name=region_name)
```
