### ISSUE TITLE
Path of utilities inside plugins folder is different in local runner and MWAA

### ISSUE THREAD

**Issue by SanketSanath** [aws/aws-mwaa-local-runner#199]
My folder structure is like this-
```
.
├── dags/
└── plugins/
    └── utils/
        └── common_utilities.py
```

On local runner I am able to import the common utility file as `from utils.common_utilities import timer_func` while when I upload plugins.zip to MWAA, I have to use `from plugins.utils.common_utilities import timer_func`.

I tried listing the contents of `/usr/local/airflow/plugins` on both local and MWAA and found that both store plugins differently.
Output of `os.listdir('/usr/local/airflow/plugins')` on local is `['.DS_Store', 'utils']`
While on MWAA it is `['aws_mwaa', 'celery_config.py', 'plugins']`.

How to handle this situation where for same folder structure, plugins is stored differently in local and MWAA? Do I have to change the folder that I zip or something?

**Comment by elashrry** [comment]
I think it is probably how you zip the plugins folder. Try unzip it on your local, if you find its structure as `plusgins/plugins/utils/` then you need to zip what is inside the plugins folder, not the folder itself. this is part of our CI/CD
```
cd ./plugins; zip -r plugins.zip .
aws s3 cp plugins.zip s3://$S3_BUCKET_NAME/plugins/
rm plugins.zip; cd ..
```

**Comment by SanketSanath** [comment]
Got it. Once I zipped from inside the `plugins` folder it worked.

Do you have Github CI/CD workflow to sync `dags/` folder with s3 bucket? I was looking into it and found some of the things. But if you have it handy then I wouldn't have to search further xD.

**Comment by elashrry** [comment]
I am using GItLab CI/CD, but I think you can rely on this documentation: [Migrating from GitLab CI/CD to GitHub Actions](https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-gitlab-cicd-to-github-actions) to use it with Github. 

You will need to add your test stage. You can also enable [versioning](https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html?ref_=pe_411040_118635630) on S3 to have the possibility to quickly roll back if something breaks. You can define the [lifecycle](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lifecycle-mgmt.html?ref_=pe_411040_118635630) of the files on S3 too. 
```
stages:
  - build
  - test 
  - deploy


default:
  image: python:latest
  before_script:
    - apt-get update -qy
    - apt-get -y install zip
    - pip install awscli

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"



build_requirements:
  stage: build
  script:
    - aws s3 sync --delete requirements/ s3://$S3_BUCKET_NAME/requirements/
  rules:
    - changes:
      - requirements/requirements.txt

build_dags:
  stage: build
  script:
    - aws s3 sync --delete ./dags s3://$S3_BUCKET_NAME/dags/ --exclude "*" --include "*.py"
  rules:
    - changes:
      - dags/*.py

build_plugins:
  stage: build
  script:
    - cd ./plugins; zip -r plugins.zip .
    - aws s3 cp plugins.zip s3://$S3_BUCKET_NAME/plugins/
    - rm plugins.zip; cd ..
  rules:
    - changes:
      - plugins/**/*


deploy:
  # deploy AMWAA
  stage: deploy
  script:
  # get latest version of requirements.txt
    - |
      requirements_version=$( aws s3api list-object-versions --bucket $S3_BUCKET_NAME \
      --prefix "requirements/requirements.txt" \
      --query "sort_by(Versions, &LastModified)[-1].VersionId" )
  # get latest version of plugins.zip
    - |
      plugins_version=$( aws s3api list-object-versions --bucket $S3_BUCKET_NAME \
      --prefix "plugins/plugins.zip" \
      --query "sort_by(Versions, &LastModified)[-1].VersionId" )
    - |
      aws mwaa update-environment --name $MWAA_ENV_NAME \
      --requirements-s3-path "requirements/requirements.txt" \
      --requirements-s3-object-version $requirements_version \
      --plugins-s3-path "plugins/plugins.zip" \
      --plugins-s3-object-version $plugins_version \
      --region $REGION
  rules:
    - changes:
      - plugins/**/*
      - requirements/requirements.txt
```
