### ISSUE TITLE
Cannot Open Connection tab in Airflow UI

### ISSUE THREAD

**Issue by nitindr-onetrust** [aws/aws-mwaa-local-runner#290]
I'm trying to access the connection panel in Airflow UI, but it's giving me an error as below

```
Something bad has happened.

Airflow is used by many users, and it is very likely that others had similar problems and you can easily find
a solution to your problem.

Consider following these steps:

  * gather the relevant information (detailed logs with errors, reproduction steps, details of your deployment)

  * find similar issues using:
     * [GitHub Discussions](https://github.com/apache/airflow/discussions)
     * [GitHub Issues](https://github.com/apache/airflow/issues)
     * [Stack Overflow](https://stackoverflow.com/questions/tagged/airflow)
     * the usual search engine you use on a daily basis

  * if you run Airflow on a Managed Service, consider opening an issue using the service support channels

  * if you tried and have difficulty with diagnosing and fixing the problem yourself, consider creating a [bug report](https://github.com/apache/airflow/issues/new/choose).
    Make sure however, to include all relevant details and results of your investigation so far.

Python version: 3.10.9
Airflow version: 2.5.1
Node: redact
-------------------------------------------------------------------------------
Error! Please contact server admin.
```

**Comment by nenkie76** [comment]
@nitindr-onetrust, did you try running `./mwaa-local-env reset-db` ?

**Caution**: it will reset your local PosgresDB

**Comment by nitindr-onetrust** [comment]
Hello @nenkie76 I did tried the reset command. But no yield, same issue!

**Comment by nitindr-onetrust** [comment]
The issue appears to be resolved when i change the postgress volume path in "docker-compose-local.yml" back to ${PWD}

```
postgres:
        image: postgres:10-alpine
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "${PWD}/db-data:/var/lib/postgresql/data"
```
Previously i've removed  the "${PWD}" from the volume path as i was getting some postgress database error! like below

`- "/db-data:/var/lib/postgresql/data"`
