### ISSUE TITLE
MWAA-Version-2.10.3  No module named 'airflow.providers.slack'

### ISSUE THREAD

**Issue by oluies** [aws/aws-mwaa-local-runner#423]
MWAA-Version-2.10.3 
```

   local-runner:
        container_name: ddp_mwaa_v2103
        image: amazon/mwaa-local:2_10_3
        platform: "linux/amd64"

```
Requiroments lists 
```
--constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.10.3/constraints-3.11.txt"

apache-airflow==2.10.3
apache-airflow-providers-amazon==9.0.0
apache-airflow-providers-http==4.13.2
apache-airflow-providers-slack==8.9.1
apache-airflow-providers-sqlite==3.9.0
apache-airflow-providers-common-sql==1.19.0  # Added for compatibility
apache-airflow-providers-apache-iceberg==1.1.0
apache-airflow-providers-apache-spark==4.11.2
apache-airflow-providers-dbt-cloud==3.11.1
slack_sdk==3.33.3
```

But I get 

```
/local/airflow/dags/utils/airflow_utils.py: No module named 'airflow.providers.slack'
ddp_mwaa_v2103      | [2025-02-02T14:43:34.602+0000] {{triggerer_job_runner.py:510}} INFO - 0 triggers currently running
ddp_mwaa_v2103      | [2025-02-02T14:43:41.547+0000] {{processor.py:401}} WARNING - Error when trying to pre-import module 'airflow.providers.slack.operators.slack_webhook' found in /usr/local/airflow/dags/utils/airflow_utils.py: No module named 'airflow.providers.slack'
```
