### ISSUE TITLE
Apply network_mode: "host" to local runner to allow access to outside RDS with PostgresOperator?

### ISSUE THREAD

**Issue by FergusDevelopmentLLC** [aws/aws-mwaa-local-runner#97]
Hi,

I am somewhat new to docker and airflow in an aws context. I am trying to create a test dag that will using your runner that can access an outside aws rds with a PostgresOperator.

I have successfully built the code for the test airflow:

```
$ sudo ./mwaa-local-env build-image
...
Step 25/25 : CMD ["local-runner"]
---> Using cache
---> 3e9b553c5196
Successfully built 3e9b553c5196
Successfully tagged amazon/mwaa-local:2.0.2

```
I can start the airflow ui:

```
$ sudo ./mwaa-local-env start
[+] Running 2/0
 ⠿ Container docker-postgres-1      Created                                                                                                                                                0.0s
 ⠿ Container docker-local-runner-1  Created                                                                                                                                                0.0s
Attaching to docker-local-runner-1, docker-postgres-1
...
docker-local-runner-1  | admin already exist in the db
docker-local-runner-1  |   *_______*       *_______*
docker-local-runner-1  |  *_    |*( )*____*  */*  /*__*      _
docker-local-runner-1  | *_* */| |_  /*  */  /_*  /_  _ \ | /| / /
docker-local-runner-1  | *_* |  /   /   _  */ _  / / // / |/ |/ /*
*docker-local-runner-1  |  //  |//  //    //    //  \_*/*__/|*/
docker-local-runner-1  | [2022-02-17 22 (tel:2022021722):45:26,182] dagbag.py:451 INFO - Filling up the DagBag from /dev/null
docker-local-runner-1  | [2022-02-17 22 (tel:2022021722):45:29 +0000] [188] [INFO] Starting gunicorn 19.10.0
docker-local-runner-1  | [2022-02-17 22 (tel:2022021722):45:29 +0000] [188] [INFO] Listening at: http://0.0.0.0:8080 (http://0.0.0.0:8080/) (188)
docker-local-runner-1  | [2022-02-17 22 (tel:2022021722):45:29 +0000] [188] [INFO] Using worker: sync
docker-local-runner-1  | [2022-02-17 22 (tel:2022021722):45:29 +0000] [191] [INFO] Booting worker with pid: 191

```

I can visit airflow UI at http://localhost:8080/home

![image](https://user-images.githubusercontent.com/1529796/154591381-a775a4a5-4355-4979-b112-1742996e0147.png)

It reflects the new tutorial_query.py that I have added in the dags folder.

In this DAG, I want to make a test query to a postgres rds OUTSIDE of the docker container AND OUTSIDE of the host with PostgresOperator. It is an AWS RDS instance.

```
from airflow import DAG
from airflow.providers.postgres.operators.postgres import PostgresOperator
from datetime import timedelta
from airflow.utils.dates import days_ago

dag_id = "test_query_v05"
task_id = "country_selection"
sql = """SELECT * FROM countries limit 10;"""

default_args = {
    'owner': 'Will',
    'depends_on_past': False,
    'start_date': days_ago(1)
}

with DAG(
    dag_id=dag_id,
    default_args=default_args,
    description='demonstration query',
    schedule_interval="0 12 * * *",
    catchup=False,
    max_active_runs=1
) as dag:

    select_some_countries = PostgresOperator(
        task_id=task_id,
        postgres_conn_id='XXXXXX',
        sql=sql,
        execution_timeout=timedelta(hours=2)
    )
    select_some_countries

```

I have created the XXXXXX postgres_conn_id in the Admin area of Airflow.

![image](https://user-images.githubusercontent.com/1529796/154592031-49890cf3-ddb5-4649-b144-9c8f208476e9.png)

I trigger the DAG, it fails. In the DAG run log, I get the following error.

```
Traceback (most recent call last):
    ...
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "eXXXXXXXXXXXXus-east-1.rds.amazonaws.com" to address: Name or service not known
[2022-02-17 23:00:00,456] {{taskinstance.py:1532}} INFO - Marking task as FAILED. dag_id=test_query_v05, task_id=country_selection, execution_date=20220217T225937, start_date=20220217T225940, end_date=20220217T230000
[2022-02-17 23:00:00,508] {{local_task_job.py:146}} INFO - Task exited with return code 1
```

It cannot connect to the outside rds for some reason. First, I think the container cannot translate eXXXXXXXXXXXXus-east-1.rds.amazonaws.com to ip. A dns issue.

I am able to see the ip address for eXXXXXXXXXXXXus-east-1.rds.amazonaws.com using nslookup on the host:

```
$ nslookup eXXXXXXXXXXXXus-east-1.rds.amazonaws.com 
Non-authoritative answer:
Name:   eXXXXXXXXXXXXus-east-1.rds.amazonaws.com
Address: 10.XXX.XXX.156
```

Also, I can query the endpoint from the host using pgadmin4.

I hard code the rds endpoint ip in the Airflow UI Admin, adding the XXXXX connection:

This time the error is...

```
psycopg2.OperationalError: connection to server at "10.XXX.XXX.156", port 5432 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?
[2022-02-17 23:14:00,445] {{taskinstance.py:1532}} INFO - Marking task as FAILED. dag_id=test_query_v05, task_id=country_selection, execution_date=20220217T231148, start_date=20220217T231149, end_date=20220217T231400
[2022-02-17 23:14:00,522] {{local_task_job.py:146}} INFO - Task exited with return code 1
```

So, I think it's not a dns issue.

In another similar context (pgadmin4 in a docker container), I had to specify the network as host on the docker container. This allowed the containerized pgadmin4 web app query with the same access as the host.

When I try to do the same in the runner.

By adding network_mode: "host" to docker-compose-local.yml in the local-runner service:

```
version: '3.7'
services:
    postgres:
        image: postgres:10-alpine
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "${PWD}/db-data:/var/lib/postgresql/data"

    local-runner:
        image: amazon/mwaa-local:2.0.2
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ${PWD}/dags:/usr/local/airflow/dags
            - ${PWD}/plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        network_mode: "host"
        command: local-runner
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
```

When add network_mode: "host", the local-runner can no longer connect to postgres:10-alpine container and I cannot start the web ui.

```
Attaching to docker-local-runner-1, docker-postgres-1
docker-postgres-1      | 
docker-postgres-1      | PostgreSQL Database directory appears to contain a database; Skipping initialization
docker-postgres-1      | 
docker-postgres-1      | 2022-02-17 23:41:04.304 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
docker-postgres-1      | 2022-02-17 23:41:04.304 UTC [1] LOG:  listening on IPv6 address "::", port 5432
docker-postgres-1      | 2022-02-17 23:41:04.308 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
docker-postgres-1      | 2022-02-17 23:41:04.336 UTC [21] LOG:  database system was shut down at 2022-02-17 23:40:54 UTC
docker-postgres-1      | 2022-02-17 23:41:04.344 UTC [1] LOG:  database system is ready to accept connections
docker-local-runner-1  | Thu Feb 17 23:41:45 UTC 2022 - waiting for Postgres... 1/20 <--------------------------------------eventually times out.
```

Any ideas of how I might work around this issue or if you see another angle, please let me know.

Thank you! Very useful tool!
